# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4TopfG0ACLQDjddepFwTV2iCcPxeC6I
"""

import random

choices = ["rock", "paper", "scissors"]

user = input("Enter rock/paper/scissors: ")
computer = random.choice(choices)

print("Computer:", computer)

if user == computer:
    print("Tie")

elif (user == "rock" and computer == "scissors") or \
     (user == "paper" and computer == "rock") or \
     (user == "scissors" and computer == "paper"):
    print("You Win")

else:
    print("You Lose")